# Generated by Django 4.0 on 2023-02-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudent',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='school',
        ),
        migrations.DeleteModel(
            name='HistoricalSchool',
        ),
        migrations.DeleteModel(
            name='HistoricalStudent',
        ),
    ]
