# Generated by Django 4.0 on 2023-02-01 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicalstudent_historicalschool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudent',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='school',
        ),
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='HistoricalSchool',
        ),
        migrations.DeleteModel(
            name='HistoricalStudent',
        ),
    ]
